version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=school
      - POSTGRES_USER=oroz
      - POSTGRES_PASSWORD=123
web:
  build: .
  command: python manage.py 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000.8000"
  depends_on:
    - db